### ISSUE TITLE
Third Programming - Array

### ISSUE THREAD

**Issue by JinseobBae** [hb9301/simple-study-review#4]
파일명 : ArraySolutionOOO3.java

1번문제  (https://programmers.co.kr/learn/courses/30/lessons/12915)

문자 내 마음대로 정렬하기

[문제]
![image](https://user-images.githubusercontent.com/29051992/114302520-67e27180-9b04-11eb-8d7d-ebc3f4bc9e97.png)

[제한조건]
![image](https://user-images.githubusercontent.com/29051992/114302546-85174000-9b04-11eb-9218-43dba6d873f1.png)

[예시]
![image](https://user-images.githubusercontent.com/29051992/114302565-8e081180-9b04-11eb-8ded-71cf6275653d.png)

2번문제(https://programmers.co.kr/learn/courses/30/lessons/1845)

폰캣몬

[문제]
![image](https://user-images.githubusercontent.com/29051992/114302658-f35c0280-9b04-11eb-96d3-6e40484ff659.png)

[제한조건]
![image](https://user-images.githubusercontent.com/29051992/114302675-feaf2e00-9b04-11eb-9c93-6aaff478959a.png)

[예시]
![image](https://user-images.githubusercontent.com/29051992/114302680-04a50f00-9b05-11eb-9d85-c92964bd1529.png)

**Comment by sbpaeng** [comment]
홍박사님 너무한거 아닙니까 주기 싫으면 말로하지
