### ISSUE TITLE
4th Programming - stack/queue

### ISSUE THREAD

**Issue by sbpaeng** [hb9301/simple-study-review#5]
https://programmers.co.kr/learn/courses/30/lessons/42583

![image](https://user-images.githubusercontent.com/81783776/114524245-03e4b800-9c80-11eb-93e5-59bd8b90e8d6.png)

![image](https://user-images.githubusercontent.com/81783776/114524278-0b0bc600-9c80-11eb-9763-2e23dcb33a88.png)

![image](https://user-images.githubusercontent.com/81783776/114526365-e0bb0800-9c81-11eb-852e-d862609f1028.png)

**Comment by hb9301** [comment]
![image](https://user-images.githubusercontent.com/81724627/115361656-bde9a000-a1fb-11eb-9fa0-caab46c8c19b.png)
